// Packages
import Head from 'next/head';
import { Inter } from '@next/font/google';

// MUI
import { styled } from "@mui/material/styles";
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';

// Components
import SearchBox from '@/components/SearchBox';

// Font
const inter = Inter({ subsets: ['latin'] })

// Image
import bgImage from "@/public/images/the-eiffel-tower-paris.jpg";

// Styled components
const HomeWrapper = styled('main')(({ theme }) => ({
  height: '100vh',
  position: 'relative',
  overflow: 'hidden'
}));
const Title = styled('h1')(({ theme }) => ({
  color: '#333',
  textAlign: 'center',
  maxWidth: '80%',
  display: 'flex',
  flexDirection: 'column',
  gap: '20ox',

  span: {
    fontSize: 50,
    lineHeight: 0.85,
  },
  p: {
    margin: '8px 0 0',
    fontSize: 18,
  }
}));

/**
 * Custom styles
 * CS refers to custom styles
 */
const containerCS = {
  display: 'flex',
  flexWrap: 'wrap',
  alignItems: 'center',
  justifyContent: 'space-between',
  height: '100%',
  maxWidth: '1600px !important'
};

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Mozio - Distance Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeWrapper className={inter.className}>
        <Container fixed sx={containerCS}>
          <Grid container spacing={6} alignItems="start">
            <Grid item xs={12} lg={6}>
              <Box
                display={{ xs: "none", lg: "flex" }}
                width="calc(100% - 2rem)"
                height="calc(100vh - 2rem)"
                borderRadius="lg"
                ml={2}
                mt={2}
                sx={{
                  background: `url(${bgImage.src}) no-repeat center center`,
                  backgroundSize: 'cover',
                  width: 'calc(100 % - 2rem)',
                  height: 'calc(100vh - 2rem)',
                  borderRadius: '0.5rem',
                  boxShadow: 'none'
                }}
              />
            </Grid>
            <Grid
              item
              xs={12}
              lg={6}
              sx={{
                display: 'flex',
                flexDirection: 'column',
                gap: '50px',
                alignItems: 'center',
                marginTop: '60px'
              }}
            >
              <Title>
                <span>Mozio Distance Calculator</span>
                <p>Determine the precise distance between two cities.</p>
              </Title>
              <SearchBox />
            </Grid>
          </Grid>
        </Container>
      </HomeWrapper>
    </>
  )
}